[package]
authors = ["Lucio Franco <luciofranco14@gmail.com>"]
category = ["async"]
description = "Tokio 0.2 compat utilities"
edition = "2018"
name = "tokio-compat-02"
version = "0.1.0"

[dependencies]
once_cell = "1.4"
pin-project-lite = "*"
tokio_02 = {version = "0.2", package = "tokio", features = ["rt-threaded"]}

[dev-dependencies]
hyper = "0.13"
tokio = {version = "0.3", git = "https://github.com/tokio-rs/tokio", features = ["full"]}
